Feature/mobile menu
SoftRyzen-internship/gift-studio pull request #11
Opened 2024-01-07 16:22 UTC by TrueMolni

Привіт, ось варіант мобільного меню. Ще працюю над ним, але поглянь, чи впорядку. Потім додам кнопку мобільного меню як окремий компонент. Кидаю зараз, щоб легше було доповнити чи иправити

2024-01-07 17:41 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu.tsx
всі компоненти в папках, не окремо

2024-01-07 17:42 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu.tsx
> +        className="max-w-[24px] max-h-[24px] block lg:hidden z-60 relative"
мабуть точніше без макс, просто w-[24px]...

2024-01-07 17:54 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu.tsx
> +          <a
телефон у нас перевикористовуваний кеомпонет (з іконкою), він 3 раза десь на сайті

2024-01-07 17:56 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:max-w-[508px] lg:max-h-[20px]";
синтаксис тут правильний, але неправильно що фіксуємося під тільки це меню. Пункт якщо додамо - треба шукати де міняти розміри.

2024-01-07 18:07 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu.tsx
> +        flex flex-col items-center lg:hidden sm:pt-[24px] sm:px-[20px] md:px-[30px] md:pt-[36px]"
якщо че чернетка- можу помилятись. У нас mobile-first, не зрозумів в яке місце йдуть паддінги, але можливо sm: у нас рідко використувується, або ніколи

2024-01-07 18:21 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu.tsx
> +          <div className="flex sm:justify-between w-full pointer-events-auto sm:mb-[40px] mb-[64px]">
sm: у нас мабуть рідко використувується, або ніколи.
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/58699786/cbaac214-b37c-4b6e-827d-67750c854b2c)

2024-01-08 08:06 UTC, TrueMolni commented on src/components/ui/MobileMenu.tsx
> +          <a
Так, але я ще не робив цей компонент, була задача тільки по мобільному меню, це заглушка

2024-01-08 08:08 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:max-w-[508px] lg:max-h-[20px]";
Можна, просто якщо по контенту, то буде 505 ширини, не 508

2024-01-08 08:10 UTC, TrueMolni commented
Передивлюсь правки і виправлю. Сьогодні робитиму також компонент списку контактів та со мереж і вставлю замість заглушки

2024-01-09 11:38 UTC, sergio-nezhigay commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +type MobileBtnProps = {
окремий файл

2024-01-09 11:39 UTC, sergio-nezhigay commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +"use client";
порядок імпортів - від віддалених, далі компоненти, типи, утиліти, стилі, іконки.. (все - через переноси)

2024-01-09 11:40 UTC, sergio-nezhigay commented on src/app/page.tsx
> +import React from "react";
порядок імпортів - від віддалених, далі компоненти, типи, утиліти, стилі, іконки.. (все - через переноси)

2024-01-09 11:40 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +"use client";
порядок імпортів - від віддалених, далі компоненти, типи, утиліти, стилі, іконки.. (все - через переноси)

2024-01-09 11:42 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +type navProps = {
типи в окремих файлах - не в компонентах. також назва. -як варіант "NavProps"

2024-01-09 11:43 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +const MobileMenu = ({ isMobile }: navProps) => {
не підходить під приклад синтаксису компонента

2024-01-09 11:43 UTC, sergio-nezhigay commented on src/app/page.tsx
>  export default function Home() {
не підходить під приклад синтаксису компонента

2024-01-09 11:44 UTC, sergio-nezhigay commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +const MobileBtn = ({ isMobileMenuShown, handleClick }: MobileBtnProps) => {
не підходить під приклад синтаксису компонента

2024-01-09 11:51 UTC, sergio-nezhigay commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +import Navbar from "../NavBar/NavBar";
має бути типу "@/components". без ".."

2024-01-09 11:53 UTC, sergio-nezhigay commented on src/app/page.tsx
> +  };
перед строчкою "return" в компонентах - теж пуста строчка

2024-01-09 11:58 UTC, sergio-nezhigay requested changes
проставив коментарі, більше по стилях

2024-01-09 12:03 UTC, TrueMolni commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +type MobileBtnProps = {
Є

2024-01-09 12:03 UTC, TrueMolni commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +"use client";
Є

2024-01-09 12:04 UTC, TrueMolni commented on src/app/page.tsx
> +import React from "react";
Є

2024-01-09 12:04 UTC, TrueMolni commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +"use client";
Є

2024-01-09 12:09 UTC, TrueMolni commented on src/components/ui/MobileBtn/MobileBtn.tsx
> +const MobileBtn = ({ isMobileMenuShown, handleClick }: MobileBtnProps) => {
Є

2024-01-09 12:20 UTC, TrueMolni commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +import Navbar from "../NavBar/NavBar";
Є

2024-01-09 12:20 UTC, TrueMolni commented on src/app/page.tsx
> +  };
Є

2024-01-09 12:24 UTC, TrueMolni commented
Вніс корективи

2024-01-10 08:00 UTC, sergio-nezhigay approved these changes

2024-01-10 10:41 UTC, sergio-nezhigay approved these changes

2024-01-10 10:42 UTC, merged