add contacts list, phone link, social media links
SoftRyzen-internship/gift-studio pull request #13
Opened 2024-01-08 13:28 UTC by TrueMolni

2024-01-08 14:13 UTC, sergio-nezhigay commented on src/components/ui/ContactsList/ContactsList.tsx
> +          className="flex items-center gap-2 text-xl"
додай плз hover та focus обробку

2024-01-08 14:17 UTC, sergio-nezhigay commented on src/components/ui/PhoneLink/PhoneLink.tsx
> +      className={"flex items-center gap-2 text-xl " + customStyle}
не має бути undefined типу "flex items-center gap-2 text-xl undefined"

2024-01-08 14:23 UTC, sergio-nezhigay commented on src/components/ui/PhoneLink/PhoneLink.tsx
> +      target="_blank"
для телефону не треба

2024-01-08 14:23 UTC, sergio-nezhigay commented on src/components/ui/PhoneLink/PhoneLink.tsx
> +      rel="noopener noreferrer nofollow"
для телефону не треба

2024-01-08 14:29 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +type socialMediaList = {
по назві незрозуміло що це - тип

2024-01-08 14:32 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +            aria-label={contacts.emailData.ariaLabel}
aria-label неправильний зміст, бачу "Контактна електронна адреса компанії"

2024-01-08 14:34 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +          <a
додай плз hover та focus обробку

2024-01-08 15:09 UTC, TrueMolni commented on src/components/ui/ContactsList/ContactsList.tsx
> +          className="flex items-center gap-2 text-xl"
Додав

2024-01-08 16:51 UTC, TrueMolni commented
Зробив зміни, перевір. Програвся з і стилями, нічого не вирішило проблему, усі іконки замальовуються правильно, тільки з фейсбуком біда)

2024-01-09 07:10 UTC, sergio-nezhigay commented on src/components/ui/ContactsList/ContactsList.tsx
> +          <EmailIcon className="w-6 h-6 fill-current text-white transition group-hover:text-accent" />
мені здається що ховер красивіше якщо він міняє чорний на білий. І так в тз. Також немає фокусу

2024-01-09 07:42 UTC, sergio-nezhigay requested changes

2024-01-09 07:42 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +      className="w-6 h-6 fill-current text-white transition group-hover:text-accent"
чорний на білий. І так в тз. Також немає фокусу

2024-01-09 07:42 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +      className="w-6 h-6 fill-current text-white transition group-hover:text-accent"
Іконку не видно - просто чотирикутник. як не вийде-напиши..
чорний на білий. І так в тз. Також немає фокусу

2024-01-09 09:45 UTC, TrueMolni commented
Зробив зміни в іконках, тепер вони не замальовується, а тільки їх лінії, залишив закоментований код, щоб в разі чого, повернути назад. Як варіант підходить приберу. Іконка фейсбуку стала прозора всередині, а у іконки інстаграму пропадає кружечок, інакше ніяк

2024-01-10 09:44 UTC, sergio-nezhigay commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +type socialMediaListType = {
має бути в окремому файлі та назва неправильно

2024-01-10 09:45 UTC, sergio-nezhigay commented on src/app/page.tsx
> +"use client";
убрати з головної сторінки

2024-01-10 11:24 UTC, TrueMolni commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +type socialMediaListType = {
виправив

2024-01-10 11:24 UTC, TrueMolni commented on src/app/page.tsx
> +"use client";
домовились, поки буде так

2024-01-10 11:34 UTC, TrueMolni commented
Вніс корективи

2024-01-10 11:41 UTC, sergio-nezhigay approved these changes

2024-01-10 11:42 UTC, merged