Dev
SoftRyzen-internship/gift-studio pull request #14
Opened 2024-01-08 15:31 UTC by sergio-nezhigay

tailwind init, section class, logo, images upload, heading(title) component and button

2024-01-09 09:47 UTC, nadiakhoptiuk requested changes

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/app/layout.tsx
> +import Header from "@/sections/Header";
порядок імпортів - від віддалених, далі компоненти, типи, утиліти, стилі, іконки.. (через переноси)

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/app/globals.css
>    font-family: var(--font-caveat);
змінні ти вже підключив у конфігу.
я б казала перейменувати шрифти в конфігу на їх назви сімейств, і тут використовувати з тейлвінда, те саме для body, приклад: 

 body {
    @apply font-montserrat;
  }
  
  спробувала, уже нормально запити за шрифтами ідуть.

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/SectionHeading/SectionHeading.tsx
> +import { SectionHeadingProps } from "./types";
робіть відступи між зовнішніми та внутрішніми імпортами

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/SectionHeading/SectionHeading.tsx
цей компонент можна винести в папку ui або в ідеалі - typography

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/SectionHeading/SectionHeading.tsx
> +        "text-4xl md:text-5xl lg:text-7xl text-accent text-center font-display font-normal",
тут можна одразу додати нижні відступи, оскільки вони однакові

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +import { ButtonLinkProps } from "./types";
порядок імпортів, відступи

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/app/globals.css
>    .flex-center {
додати клас для переходів, щоб всі тривалості були однакові, 250-300 приблизно

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
не бачу міні-документації, як використовувати цей компонент, що значить варіант і в яких випадках який писати.
додайте readme.md

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/data/common.json
> +  "companyName": "Gift Studio",
можна винести в обєкт logo ці ключі, щоб було зручніше для користування

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/sections/Header/Header.tsx
> +    <header className="flex-between container py-6 md:py-9">
невірно обмежувати хедер класом контейнер.
контейнер повинен знаходитись всередині секції, а секція, хедер і футер (які також є секціями по суті) повинні тягнутися на всю ширину. вертикальні падінги залишаємо на секціях, горизонтальні на контейнер

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/sections/Gallery/placeholder
цю папку видалити

найменувати секції можна просто Gallery, About, оскільки вони уже знаходяться в папці sections

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/sections/Header/Header.tsx
хедер і футер краще винести для зручності у src/layout

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/NavBar.tsx
для цього компонента потрібна папка з усіма необхідними файлами

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/NavBar.tsx
> +type navData = {
відступи і форматування коду повинно зберігатися, це полегшує читабельність

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/NavBar.tsx
> +type navProps = {
усі типи найменуються з великої літери
тімліду завдання: узгодити найменування до кінця

2024-01-09 09:47 UTC, nadiakhoptiuk commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:w-max[508px] lg:h-max[20px]";
висоту і ширину ніде не обмежуємо

2024-01-09 10:16 UTC, nadiakhoptiuk requested changes

2024-01-09 10:16 UTC, nadiakhoptiuk commented on src/components/ui/Logo/Logo.tsx
> +      className="group flex items-center gap-x-2 font-sans text-base font-normal text-black transition-colors hover:text-accent focus:text-accent lg:text-3xl"
тут домовились переробити, на ховер не змінюється колір, лише scale +10%

2024-01-09 10:16 UTC, nadiakhoptiuk commented on src/sections/AboutSection/AboutSection.tsx
> +    <section id={id} className="section container">
невірно обмежувати хедер класом контейнер.
контейнер повинен знаходитись всередині секції, а секція, хедер і футер (які також є секціями по суті) повинні тягнутися на всю ширину. вертикальні падінги залишаємо на секціях, горизонтальні на контейнер

2024-01-09 10:16 UTC, nadiakhoptiuk commented on src/sections/GallerySection/GallerySection.tsx
> +    <section id={id} className="section container">
невірно обмежувати хедер класом контейнер.
контейнер повинен знаходитись всередині секції, а секція, хедер і футер (які також є секціями по суті) повинні тягнутися на всю ширину. вертикальні падінги залишаємо на секціях, горизонтальні на контейнер

2024-01-09 10:27 UTC, sergio-nezhigay commented on src/app/layout.tsx
> +import Header from "@/sections/Header";
зробив для layout.tsx

2024-01-09 10:27 UTC, sergio-nezhigay commented on src/app/globals.css
>    font-family: var(--font-caveat);
зробив

2024-01-09 10:31 UTC, sergio-nezhigay commented on src/components/SectionHeading/SectionHeading.tsx
зробив

2024-01-09 10:34 UTC, sergio-nezhigay commented on src/sections/Header/Header.tsx
зробив

2024-01-09 11:03 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
+

2024-01-09 11:13 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +type navData = {
Зроблено

2024-01-09 11:14 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +type navProps = {
Зробив

2024-01-09 11:18 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:w-max[508px] lg:h-max[20px]";
Змінив

2024-01-09 13:16 UTC, BlackyHat commented on src/sections/GallerySection/GallerySection.tsx
> +    <section id={id} className="section container">
ok. fixed in pr feature/faq

2024-01-09 13:16 UTC, BlackyHat commented on src/sections/AboutSection/AboutSection.tsx
> +    <section id={id} className="section container">
ok. fixed in pr feature/faq

2024-01-09 13:17 UTC, BlackyHat commented on src/components/ui/Logo/Logo.tsx
> +      className="group flex items-center gap-x-2 font-sans text-base font-normal text-black transition-colors hover:text-accent focus:text-accent lg:text-3xl"
ok.
already done. 
fixed in pr feature/slider

2024-01-09 13:18 UTC, BlackyHat commented on src/sections/Header/Header.tsx
> +    <header className="flex-between container py-6 md:py-9">
ok. 
fixed in pr feature/faq

2024-01-09 13:21 UTC, BlackyHat commented on src/sections/Gallery/placeholder
ok. fixed in pr feature/faq

2024-01-09 13:22 UTC, BlackyHat commented on src/data/common.json
> +  "companyName": "Gift Studio",
companyName -може ще десь по додатку використовуватися

2024-01-09 13:50 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
ok.
already done.
fixed in pr feature/slider

2024-01-09 14:09 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +import { ButtonLinkProps } from "./types";
ok.
fixed in pr feature/faq

2024-01-09 14:13 UTC, BlackyHat commented on src/components/SectionHeading/SectionHeading.tsx
> +import { SectionHeadingProps } from "./types";
ok.
fixed in pr feature/faq

2024-01-09 14:16 UTC, BlackyHat commented on src/components/SectionHeading/SectionHeading.tsx
> +        "text-4xl md:text-5xl lg:text-7xl text-accent text-center font-display font-normal",
В секцї About іншіЖ Tablet, Desktop
ok.
fixed in pr feature/faq

2024-01-09 14:52 UTC, BlackyHat commented on src/data/common.json
> +  "companyName": "Gift Studio",
виніс в обєкт logo ці ключі

2024-01-10 06:18 UTC, sergio-nezhigay commented on src/app/globals.css
>    .flex-center {
поставив 300 як default в tailwind.config.ts

2024-01-10 09:20 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
add in bugfix/navbar

2024-01-11 15:19 UTC, nadiakhoptiuk approved these changes

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/app/globals.css
> +  @apply font-montserrat text-[#000000];
колір додати в змінні тейлвінд конфігу

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/data/common.json
> +  "instagramLink": "https://www.instagram.com/"
link є у contacts.json

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/app/globals.css
> +  background: -webkit-linear-gradient(180deg, #c84b4c 9.21%, #672e66 39.47%);
усі кольори треба винести в тейлвінд конфіг

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/app/globals.css
> +  -webkit-text-fill-color: #e42c2c;
усі кольори треба винести в тейлвінд конфіг

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ContactsList/ContactsList.tsx
> +        <PhoneLink />
ця лішка висотою 31, а інша 24, невірно центруються

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +      "text-white text-base font-bold bg-accent py-4 px-6 rounded-[10px] hover:bg-lava",
фокусування також потрібно описати для двох варіантів кнопок

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +            <a
чому б тут не використати компонент SocialLink?

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/NavBar/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex w-fit h-fit";
тут в обох рядках флекс не потрібен, всередині nav тільки один елемент

в першому можна замінити на max-lg:hidden

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/Logo/Logo.tsx
> +      className="group flex items-center gap-x-2 font-montserrat text-base font-normal text-black transition-transform hover:scale-110 focus:scale-110 lg:text-3xl"
перевірити блоковість, scale спрацьовує при ховері на велику площу

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +    <Link
додати href="/" для фокусування з клавіатури

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/layout/Header/Header.tsx
> +      <div className="flex-between container">
flex-between не працюватиме без flex

і такої властивості немає взагалі, або justify-between, або content-between

плюс після додання кнопки ви побачите, що ця властивість нам скоріш за все не підійде, бо у нас центрується навбар, а відступи по боках різні

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +        <div className="pointer-events-auto mb-[64px] flex w-full flex-col text-center sm:mb-[40px] sm:justify-between">
зайвий нижній марджин

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +          <a
посилання замінити компонентом

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +      <Link
це не некст лінк (для внутрішнього раутингу додатку), а зовнішнє посилання

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        className="flex flex-col gap-3 transition-all hover:text-accent focus:text-accent lg:gap-6"
на ховер і фокус ще скейл 10%

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        <ReactMarkdown className="flex flex-col items-center text-xl leading-[26.8px] md:text-3xl md:leading-[32.1px] ">
в ідеалі повернути не два параграфи, а один (огорнути), а p замінити на спани

для цього можна дещо змінити компоненти: https://www.npmjs.com/package/react-markdown#appendix-b-components

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/types.ts
> +  alt: string;
для зручності опціональні пропси вказуються в кінці

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/Slider/Slider.tsx
> +        speed={1000}
тут явно забагато, довго чекати, слайд вже майже не рухається, але кнопка також не перемикає далі

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/sections/Gallery/Gallery.tsx
> +      sizes="(max-width: 767px) 100vw, (min-width: 768px) 60vw, (min-width: 1280px) 50vw"
треба перевірити розміри, бо на компютері вантажить картинки 1920 мінімум, якщо їх є по 2-4 у секції. можливо, порядковість правил змінити.. 

а взагалі тут краще кастомно передавати, бо всі слайдери різні. можна картинку вставляти як чілдрен у слайдер

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import ArrowIcon from "@/public/assets/icons/icon-arrow-left.svg";
іконки імпортуємо в кінці

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/SliderNavButton/SliderNavButton.tsx
> +        "h-6 w-6 cursor-pointer text-gray transition hover:text-accent flex-center",
додати фокусування

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
> +        "flex flex-col text-left gap-1 md:gap-2 transition border-none max-md:px-4 max-md:py-6 md:max-lg:p-8 lg:pr-4 lg:pl-8 lg:py-8 rounded-3xl bg-latte cursor-pointer",
border-none не анімується на відміну від border-transparent
також додати властивості border-solid border-[1px], бо зараз вони існують тільки у активного

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
> +      {isActive && (
тут відбувається монтаж і демонтаж елемента, тому анімації жодної не буде. можна приховувати елемент у дереві певним чином, щоб розгортання відбувалось плавно

2024-01-11 15:19 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
> +    <li
бажано зробити елементи інтерактивними для фокусу з клавіатури

2024-01-11 15:20 UTC, merged

2024-01-11 15:25 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> +        "h-6 w-6 cursor-pointer text-gray transition hover:text-accent flex-center",
ok

2024-01-11 15:25 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import ArrowIcon from "@/public/assets/icons/icon-arrow-left.svg";
ok

2024-01-11 15:28 UTC, BlackyHat commented on src/data/common.json
> +  "instagramLink": "https://www.instagram.com/"
ok

2024-01-11 15:33 UTC, BlackyHat commented on src/app/globals.css
> +  background: -webkit-linear-gradient(180deg, #c84b4c 9.21%, #672e66 39.47%);
ok

2024-01-11 15:34 UTC, BlackyHat commented on src/app/globals.css
> +  -webkit-text-fill-color: #e42c2c;
ok

2024-01-11 15:36 UTC, BlackyHat commented on src/components/TabListIem/TabListIem.tsx
> +        "flex flex-col text-left gap-1 md:gap-2 transition border-none max-md:px-4 max-md:py-6 md:max-lg:p-8 lg:pr-4 lg:pl-8 lg:py-8 rounded-3xl bg-latte cursor-pointer",
додав анімацію і поділив на 2 компоненти з різними стилями

2024-01-11 15:36 UTC, BlackyHat commented on src/components/TabListIem/TabListIem.tsx
> +      {isActive && (
додав анімацію і поділив на 2 компоненти з різними стилями

2024-01-11 15:43 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +      "text-white text-base font-bold bg-accent py-4 px-6 rounded-[10px] hover:bg-lava",
ok

2024-01-11 15:44 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> +    <Link
ok

2024-01-11 15:47 UTC, BlackyHat commented on src/sections/Gallery/Gallery.tsx
> +      sizes="(max-width: 767px) 100vw, (min-width: 768px) 60vw, (min-width: 1280px) 50vw"
в сладері всі елементи огортаються в свій контейнер додатково -тому так

дана композиція для прикладу зображення а не робочий елемент

2024-01-11 15:47 UTC, BlackyHat commented on src/components/TabListIem/TabListIem.tsx
> +    <li
ok

2024-01-11 15:58 UTC, BlackyHat commented on src/layout/Header/Header.tsx
> +      <div className="flex-between container">
header допрацьований в іншому PR

2024-01-11 15:59 UTC, BlackyHat commented on src/components/ui/Logo/Logo.tsx
> +      className="group flex items-center gap-x-2 font-montserrat text-base font-normal text-black transition-transform hover:scale-110 focus:scale-110 lg:text-3xl"
header допрацьований в іншому PR

2024-01-11 16:02 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +        speed={1000}
ok

2024-01-12 09:15 UTC, TrueMolni commented on src/components/ui/ContactsList/ContactsList.tsx
> +        <PhoneLink />
Виправив в bugfix/dev

2024-01-12 11:26 UTC, TrueMolni commented on src/components/ui/SocialMediaList/SocialMediaList.tsx
> +            <a
зробив в bugfix/dev

2024-01-12 11:44 UTC, TrueMolni commented on src/components/ui/NavBar/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex w-fit h-fit";
виправив в bugfix/dev

2024-01-12 11:45 UTC, TrueMolni commented on src/components/ui/ContactsList/ContactsList.tsx
> +        <PhoneLink />
виправив в bugfix/dev

2024-01-12 11:46 UTC, TrueMolni commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +        <div className="pointer-events-auto mb-[64px] flex w-full flex-col text-center sm:mb-[40px] sm:justify-between">
Зроблено в іншому PR

2024-01-12 11:52 UTC, TrueMolni commented on src/components/ui/MobileMenu/MobileMenu.tsx
> +          <a
Зроблено в PR header

2024-01-12 11:57 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +      <Link
виправив в  bugfix/dev

2024-01-12 12:06 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        className="flex flex-col gap-3 transition-all hover:text-accent focus:text-accent lg:gap-6"
зробив в bugfix/dev

2024-01-12 12:09 UTC, TrueMolni commented on src/components/ui/ServiceCard/types.ts
> +  alt: string;
зробив в bugfix/dev

2024-01-15 09:28 UTC, nadiakhoptiuk commented on src/components/ui/Logo/Logo.tsx
> +      className="group flex items-center gap-x-2 font-montserrat text-base font-normal text-black transition-transform hover:scale-110 focus:scale-110 lg:text-3xl"
це потрібно робити у компоненті лого

2024-01-15 09:46 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +      <Link
не виправлено

2024-01-15 11:36 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
> +      {isActive && (
анімація акордеона не відпрацьовує

2024-01-15 13:43 UTC, sergio-nezhigay commented on src/app/globals.css
> +  @apply font-montserrat text-[#000000];
додав

2024-01-15 13:57 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +      <Link
й nofollow не було додано