Feature/slider
SoftRyzen-internship/gift-studio pull request #15
Opened 2024-01-09 10:15 UTC by BlackyHat

![image](https://github.com/SoftRyzen-internship/gift-studio/assets/105644022/7b1e9792-49a2-40c1-b63d-6236fce79539)
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/105644022/7ced7d22-bef4-48e2-82cd-cbfe48c08053)
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/105644022/67542cc5-1204-4576-9635-91ab2b67f27c)

refactor Logo component => replace hover color by transform-scale-[110]
refactor ButtonLink renamed elementName => targetName,
add readme desc form components
add slider component using swiper lib
   add atomic components for slider: SliderNavigation, SliderNavButton
   add in config gray color for nav icons
   add utility for config slider breakpoints by section (when we will create constants part data can be replaced there)

2024-01-09 15:57 UTC, sergio-nezhigay commented on README.md
> +| `targetName` | `undefined` | required, id of existing DOM element                                      |
ще 1-2 речення для детальності пліз

2024-01-09 15:57 UTC, sergio-nezhigay commented on README.md
> +| `variant `   | `undefined` | required, choose the name of the section: `primary`, `outline` or `ghost` |
ще 1-2 речення для детальності пліз

2024-01-09 15:59 UTC, sergio-nezhigay commented on README.md
> +| `section ` | `undefined` | required, choose the name of the section: `services`, `features`, `feedback` or `gallery` |
додай плз по 1 реченню чим відрізняється кожен варіант

2024-01-09 17:01 UTC, sergio-nezhigay commented on src/components/Slider/types.ts
> +  section: "features" | "feedback" | "gallery" | "services";
зробити окремим типом для перевикористання в getSliderOptions наприклад

2024-01-09 17:05 UTC, sergio-nezhigay commented on src/components/Slider/Slider.tsx
> +        loop={false}
сорі не зрозумів чому не true  за замовчуванням

2024-01-09 17:15 UTC, sergio-nezhigay commented on src/components/Slider/Slider.tsx
> +"use client";
відсортувати імпорти

2024-01-09 17:16 UTC, sergio-nezhigay commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import { cn } from "@/utils/cn";
відсортувати імпорти

2024-01-09 17:17 UTC, sergio-nezhigay commented on src/components/SliderNavigation/SliderNavigation.tsx
> +import { FC } from "react";
відсортувати імпорти

2024-01-09 17:19 UTC, sergio-nezhigay commented on src/sections/AboutSection/AboutSection.tsx
>  import SectionHeading from "@/components/SectionHeading";
відсортувати імпорти

2024-01-09 17:20 UTC, sergio-nezhigay commented on src/sections/GallerySection/GallerySection.tsx
> +      alt="Нашу продукти"
треба окремі описи для кожного зображення

2024-01-09 17:31 UTC, sergio-nezhigay commented on src/utils/getSliderOptions.ts
> +          slidesPerView: 2,
чомусь показує 1 слайд для цього режиму

2024-01-09 17:31 UTC, sergio-nezhigay commented on src/utils/getSliderOptions.ts
> +          slidesPerView: 3,
чомусь показує 4 слайди для цього режиму

2024-01-09 17:46 UTC, sergio-nezhigay commented on src/app/globals.css
> +  height: 386px;
може я не туди дивлюсь, але бачу для мобілок висоту 482px, для більших екранів теж інше

2024-01-09 17:49 UTC, sergio-nezhigay commented on src/components/Slider/Slider.tsx
> +      <SliderNavigation onNext={handleNext} onPrev={handlePrev} />
бачу навігацію й на мобілках, а не має бути

2024-01-09 17:52 UTC, sergio-nezhigay commented on src/components/SliderNavigation/SliderNavigation.tsx
> +        <SliderNavButton onClick={onPrev} />
щось не так з центруванням та можливо розміром кнопок

2024-01-09 17:56 UTC, sergio-nezhigay commented on src/sections/GallerySection/GallerySection.tsx
> +      <Slider slides={dataSlides.concat(dataSlides)} section="features" />
на мобілках мало бути не видно або все вертикально без свайпування. а бачу що як і інші секції працює

2024-01-09 18:01 UTC, sergio-nezhigay commented on src/app/globals.css
> +  height: 531px;
531px висота на мобілці тільки картинки, а за рахунок мабуть паддінгу реально висота 507

2024-01-09 18:16 UTC, sergio-nezhigay commented on src/app/globals.css
> +  padding-bottom: 24px !important;
може це мав буди маржин ?

2024-01-09 18:19 UTC, sergio-nezhigay commented on src/components/SliderNavButton/SliderNavButton.tsx
> +      <ArrowIcon className="h-4 w-4  [&>path]:stroke-current" />
[&>path] - не бачив та не знайшов що це таке. помилка чи скажи для чого це :)

2024-01-09 18:26 UTC, sergio-nezhigay requested changes
основна проблема - що не дуже вийшло в мене перевірити для різних типів слайдеру на різних екранах розмір слайда та кількість на екрані. Або багато помилок або я тупив, завтра може разом глянемо, але спочатку подивись окремі коменти

2024-01-10 07:56 UTC, BlackyHat commented on src/sections/GallerySection/GallerySection.tsx
> +      <Slider slides={dataSlides.concat(dataSlides)} section="features" />
ну то вже в секції налаштовується видно чи ні або стилями для конкретної секції слайдера

2024-01-10 07:56 UTC, BlackyHat commented on src/app/globals.css
> +  padding-bottom: 24px !important;
так марджин

2024-01-10 07:56 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> +      <ArrowIcon className="h-4 w-4  [&>path]:stroke-current" />
строке має міняти колір при ховері

2024-01-10 07:57 UTC, BlackyHat commented on src/app/globals.css
> +  height: 531px;
прокоментував вже - там марджін

2024-01-10 07:57 UTC, BlackyHat commented on src/components/SliderNavigation/SliderNavigation.tsx
> +        <SliderNavButton onClick={onPrev} />
що не так?

2024-01-10 07:58 UTC, BlackyHat commented on src/app/globals.css
> +  height: 386px;
знову повтор по тому самому зауваженню - там марджін

2024-01-10 07:59 UTC, BlackyHat commented on src/sections/GallerySection/GallerySection.tsx
> +      alt="Нашу продукти"
то цього компонента ще і нема - буде коли GalleryItem створю
це для демонстарції код

2024-01-10 07:59 UTC, BlackyHat commented on src/sections/AboutSection/AboutSection.tsx
>  import SectionHeading from "@/components/SectionHeading";
ну імпорти вже ж у нас будуть сортуватися після PR16

2024-01-10 07:59 UTC, BlackyHat commented on src/components/SliderNavigation/SliderNavigation.tsx
> +import { FC } from "react";
імпорти вже ж у нас будуть сортуватися після PR16

2024-01-10 08:00 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import { cn } from "@/utils/cn";
імпорти вже ж у нас будуть сортуватися після PR16

2024-01-10 08:00 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +"use client";
імпорти вже ж у нас будуть сортуватися після PR16

2024-01-10 08:01 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +        loop={false}
тому що переваги та відгуки не вказані як безкінечні

2024-01-10 08:13 UTC, BlackyHat commented on src/components/Slider/types.ts
> +  section: "features" | "feedback" | "gallery" | "services";
ok

2024-01-10 08:13 UTC, BlackyHat commented on README.md
> +| `variant `   | `undefined` | required, choose the name of the section: `primary`, `outline` or `ghost` |
ок

2024-01-10 08:13 UTC, BlackyHat commented on README.md
> +| `targetName` | `undefined` | required, id of existing DOM element                                      |
ок

2024-01-10 10:17 UTC, sergio-nezhigay commented on src/components/SliderNavigation/SliderNavigation.tsx
> +        <SliderNavButton onClick={onPrev} />
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/58699786/95ec163d-d992-49ae-a6d6-edbb975a2560)

2024-01-10 10:18 UTC, sergio-nezhigay commented on src/components/SliderNavigation/SliderNavigation.tsx
> +        <SliderNavButton onClick={onPrev} />
також треба ховати кнопки для сервісів коли на мобілках та планшетах

2024-01-10 10:20 UTC, sergio-nezhigay commented on src/components/Slider/Slider.tsx
> +        loop={false}
ок. але й в галереї та послугах loop включений не на всіх екранах

2024-01-10 10:41 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +        loop={false}
поміняв - скрізь loop

2024-01-10 10:42 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +        loop={false}
тобто в галереї не скрізь?
Галерея: Містить заголовок та картки. Картки гортаються за допомогою слайдеру по одній, цикл гортання - безкінечний. Фото можуть додаватись/видалятись черех адмін. панель, мінамальна кількість фото - 6.

2024-01-10 10:43 UTC, BlackyHat commented on src/components/SliderNavigation/SliderNavigation.tsx
> +        <SliderNavButton onClick={onPrev} />
я ж тобі відео надсилав

2024-01-10 10:55 UTC, sergio-nezhigay approved these changes

2024-01-10 12:33 UTC, sergio-nezhigay approved these changes

2024-01-10 12:33 UTC, merged