add folder, type file, add changes to navbar
SoftRyzen-internship/gift-studio pull request #16
Opened 2024-01-09 11:46 UTC by TrueMolni

2024-01-09 18:46 UTC, sergio-nezhigay commented on src/components/ui/NavBar/types.ts
> +export type NavPropsType = {
віділяти функції переносами(пуста строяка) - не знаю чи буде це коректувати eslint

2024-01-09 18:48 UTC, sergio-nezhigay commented on src/layout/Header/Header.tsx
> +import Navbar from "@/components/ui/NavBar/NavBar";
має працювати "@/components/ui/NavBar";

2024-01-09 18:49 UTC, sergio-nezhigay requested changes
пара невеликих помилок

2024-01-10 09:10 UTC, TrueMolni commented on src/components/ui/NavBar/types.ts
> +export type NavPropsType = {
Виправив

2024-01-10 09:11 UTC, TrueMolni commented on src/layout/Header/Header.tsx
> +import Navbar from "@/components/ui/NavBar/NavBar";
Виправив, але то не мій код)

2024-01-10 09:17 UTC, TrueMolni commented
Внесено правки

2024-01-10 13:54 UTC, sergio-nezhigay approved these changes

2024-01-10 13:55 UTC, merged