add service card, type, and card data
SoftRyzen-internship/gift-studio pull request #18
Opened 2024-01-09 15:37 UTC by TrueMolni

2024-01-09 18:59 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +          className="w-[320px] md:w-[295px] h-[416px] object-cover rounded-3xl"
до розміру md ширина по батьку, не фіксована.

2024-01-09 19:20 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        className="flex flex-col gap-6 transition-all hover:text-accent focus:text-accent"
gap для мобілок інший

2024-01-09 19:25 UTC, sergio-nezhigay commented on src/data/service-card.json
> +  "alt": "для чоловіків",
перейменувати alt. 
Сам не знаю варіантів, але може є варіант зробити 1 полем, а не двома. завтра спитати

2024-01-09 19:25 UTC, sergio-nezhigay requested changes
декільки виправлень

2024-01-10 12:38 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +          className="w-[320px] md:w-[295px] h-[416px] object-cover rounded-3xl"
зробив, бордер наче не потрінбний

2024-01-10 12:55 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        className="flex flex-col gap-6 transition-all hover:text-accent focus:text-accent"
Виправив

2024-01-10 13:31 UTC, TrueMolni commented
Зробив правки, поставив в json \n, щоб поки переносило рядок

2024-01-10 14:13 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +          alt={serviceDescription}
не підходить під формат цей. зроби для alt окреме поле

2024-01-10 14:17 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        <ReactMarkdown className="flex flex-col items-center text-xl md:text-3xl ">
очікував інші Line height

2024-01-10 14:21 UTC, sergio-nezhigay commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +      className={
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/58699786/8774ee36-b863-46e1-889f-a3a337360ede)
також це зауваження є в інших твоїх деяких файлах

2024-01-10 14:47 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +          alt={serviceDescription}
додав поле

2024-01-10 14:55 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
> +        <ReactMarkdown className="flex flex-col items-center text-xl md:text-3xl ">
Додав leading

2024-01-10 15:04 UTC, TrueMolni commented
Зробив зміни, з порядком tailwind класів розберусь згодом

2024-01-10 15:24 UTC, merged