Dev
SoftRyzen-internship/gift-studio pull request #33
Opened 2024-01-12 16:07 UTC by sergio-nezhigay

виправлення з попереднього ПР,
запроси Sanity в Example, 
компоненти Лого, FAQ, галерея, Про нас,

2024-01-15 13:10 UTC, nadiakhoptiuk requested changes
!!! додатково: 

1. червона консоль, розбіжності дом-дерева, невірно вкладені теги
https://prnt.sc/Ue5zvDyv90-9

2. https://prnt.sc/YsHhhB2tLLIZ слайдер поламався

3. лінія у футері не повинна бути на всю секцію згідно з макетом:
https://prnt.sc/9DEfiEAxnoXI

4. кнопка в герої невірно спозиціонована (декстоп, таблет, мобільний). 
https://prnt.sc/lY_oHPdjZOow
https://prnt.sc/TABX-7_66RHy

5. картинка в секції Про нас сплющується і розтягується при зміні ширини екрану

2024-01-15 13:10 UTC, nadiakhoptiuk commented on package.json
>      "react-markdown": "^9.0.1",
react-markdown треба видалити, якщо ми беремо іншу лібу

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/app/fonts.ts
> +  subsets: ["cyrillic"],
латина в нас також використовується (Gift Studio, FAQ, Made by SoftRyzen, support@gift.com.ua)

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/AdvantagesItem/AdvantagesItem.tsx
> +import { AdvantagesItemProps, IComponentsIcons } from "./types";
типи - вище по коду

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
> -      href="/"
навіщо прибрали? це потрібно для фокусування з клавіатури

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/ui/ContactsList/ContactsList.tsx
>          <a
різні розміри шрифтів
https://prnt.sc/aVIFe8Tr1c_y

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/ui/ButtonLink/ButtonLink.tsx
> -      "text-white text-base font-bold bg-accent py-4 px-6 rounded-[10px] hover:bg-lava focus:bg-lava",
мабуть, невірно конфлікти фіксили. Саша додав фокусування, хтось прибрав

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/ui/Logo/Logo.tsx
> +        className
перевірка, в принципі зайва, в крайньому разі додасть порожній рядок (або використати cn утиліту)

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/layout/Header/Header.tsx
> +          <MobileBtn
24 х 24 це сама лише іконка, кнопку треба зробити в ідеалі хоча б 40, бо складно пальцем попасти
https://prnt.sc/rTLFz1DfjZP4

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/layout/Header/Header.tsx
> +      {isMobileMenuShown && (
оскільки в нас меню просто дівчик, зроби йому анімацію якусь, translate справа як варіант (по кліку)
тут рендер за умови, тому анімацію не прикрутиш. хай воно буде завжди у моб і таб версії, просто ховати в сторону

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/ui/ServiceCard/ServiceCard.tsx
>        <Link
виправити, це зовнішнє посилання, груба помилка, я вже писала

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/Slider/Slider.tsx
> +        speed={1000}
наче Олександр зменшив, хтось повернув назад?

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/SliderNavButton/SliderNavButton.tsx
> -        "h-6 w-6 cursor-pointer text-gray transition hover:text-accent focus:text-accent flex-center",
фокус чому прибрали?

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import content from "@/data/gallery.json";
іконки після всього імпортуємо, бачу, що вони були вище

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
> +        "flex flex-col text-left gap-1 md:gap-2 transition border-none max-md:px-4 max-md:py-6 md:max-lg:p-8 lg:pr-4 lg:pl-8 lg:py-8 rounded-3xl bg-latte cursor-pointer",
border-none не анімується на відміну від border-transparent

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/components/TabListIem/TabListIem.tsx
виправити назву файлу і компонента

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/data/meta.json
> +  "title": "Gift Studio – Агенція Стратегічного Маркетингу",
у нас маркетинг?

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/data/services.json
> +      "serviceDescription": "Букети\n\n для дітей",
дітей та жінок повторюється (це для тесту?)

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/sections/About/About.tsx
> +        <ul className="max-md:mb-6 md:max-lg:mb-10 lg:h-[448px] lg:overflow-auto">
по семантиці це НЕ список однотипних елементів

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.tsx
> +    <section className={css.hero}>
ширину картинки обмежити фізичними розмірами (1440)
для таблета - одне з двох - або вставляємо картинку з макету для таблета і також обмежуємо 768, або ставити з десктопа, не обмежувати і гратися з виглядом . думаю, краще перше

на мобільний викачали вірно - 480, але його тоді налаштовувати через cover, а не contain

2024-01-15 13:10 UTC, nadiakhoptiuk commented on src/sections/Hero/hero.module.css
> +  background-color: #d9d9d9;
всі ці властивості можна спокійно прописати через тейлвінд, використавши змінні для кольорів (image якщо вже так складно, можна css)

2024-01-15 13:43 UTC, BlackyHat commented on src/data/services.json
> +      "serviceDescription": "Букети\n\n для дітей",
так, для демонстрації
із саніті даними буде ок.

2024-01-15 14:04 UTC, TrueMolni commented on package.json
>      "react-markdown": "^9.0.1",
Прибрав в bugfix/styles

2024-01-15 14:04 UTC, TrueMolni commented on src/components/ui/ContactsList/ContactsList.tsx
>          <a
Виправив в bugfix/styles

2024-01-15 14:10 UTC, TrueMolni commented on src/components/ui/Logo/Logo.tsx
> +        className
Змінив в bugfix/styles

2024-01-15 14:12 UTC, BlackyHat commented on src/sections/About/About.tsx
> +        <ul className="max-md:mb-6 md:max-lg:mb-10 lg:h-[448px] lg:overflow-auto">
feature/fix-bugs

2024-01-15 14:13 UTC, sergio-nezhigay commented on src/app/fonts.ts
> +  subsets: ["cyrillic"],
додав

2024-01-15 14:14 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> -      href="/"
загубилося в чиємусь PR.
повернув
feature/fix-bugs

2024-01-15 14:14 UTC, BlackyHat commented on src/components/AdvantagesItem/AdvantagesItem.tsx
> +import { AdvantagesItemProps, IComponentsIcons } from "./types";
виправив
feature/fix-bugs

2024-01-15 14:16 UTC, BlackyHat commented on src/components/Slider/Slider.tsx
> +        speed={1000}
фікс не потрапив до цього PR
реанімую в feature/fix-bugs

2024-01-15 14:16 UTC, TrueMolni commented on src/layout/Header/Header.tsx
> +          <MobileBtn
додав ширини в bugfix/styles

2024-01-15 14:18 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> +import content from "@/data/gallery.json";
виправив
feature/fix-bugs

2024-01-15 14:19 UTC, BlackyHat commented on src/components/SliderNavButton/SliderNavButton.tsx
> -        "h-6 w-6 cursor-pointer text-gray transition hover:text-accent focus:text-accent flex-center",
певно PR не той змерджили
feature/fix-bugs

2024-01-15 14:23 UTC, BlackyHat commented on src/components/TabListIem/TabListIem.tsx
FaqList
FaqListIem

виправив в feature/fix-bugs

2024-01-15 14:24 UTC, BlackyHat commented on src/components/TabListIem/TabListIem.tsx
> +        "flex flex-col text-left gap-1 md:gap-2 transition border-none max-md:px-4 max-md:py-6 md:max-lg:p-8 lg:pr-4 lg:pl-8 lg:py-8 rounded-3xl bg-latte cursor-pointer",
виправив в feature/fix-bugs

2024-01-15 14:25 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> -      "text-white text-base font-bold bg-accent py-4 px-6 rounded-[10px] hover:bg-lava focus:bg-lava",
виправив в feature/fix-bugs

2024-01-15 14:27 UTC, BlackyHat commented on src/components/ui/ButtonLink/ButtonLink.tsx
> -      href="/"
виправив в feature/fix-bugs

2024-01-15 14:28 UTC, BlackyHat commented on src/components/ui/Logo/Logo.tsx
> +        className
виправив в feature/fix-bugs

2024-01-15 14:31 UTC, BlackyHat commented on src/data/meta.json
> +  "title": "Gift Studio – Агенція Стратегічного Маркетингу",
виправив в feature/fix-bugs

2024-01-15 14:31 UTC, BlackyHat commented on src/sections/About/About.tsx
> +        <ul className="max-md:mb-6 md:max-lg:mb-10 lg:h-[448px] lg:overflow-auto">
виправив в feature/fix-bugs

2024-01-15 14:32 UTC, TrueMolni commented on src/layout/Header/Header.tsx
> +      {isMobileMenuShown && (
Додав трансформ і виїзд меню в bugfix/styles

2024-01-15 14:47 UTC, BlackyHat commented
червона консоль, розбіжності дом-дерева, невірно вкладені теги
https://prnt.sc/Ue5zvDyv90-9

https://prnt.sc/YsHhhB2tLLIZ слайдер поламався

fixed feature/fix-bugs

2024-01-15 15:03 UTC, TrueMolni commented on src/components/ui/ServiceCard/ServiceCard.tsx
>        <Link
Виправив в bugfix/styles

2024-01-15 15:06 UTC, TrueMolni commented on src/data/meta.json
> +  "title": "Gift Studio – Агенція Стратегічного Маркетингу",
Змінив в bugfix/styles

2024-01-15 16:11 UTC, TrueMolni commented on src/sections/Hero/Hero.tsx
> +    <section className={css.hero}>
Виправив в bugfix/styles

2024-01-15 16:23 UTC, TrueMolni commented on src/sections/Hero/hero.module.css
> +  background-color: #d9d9d9;
додав в bugfix/styles

2024-01-15 16:24 UTC, TrueMolni commented
Додав виправлення

2024-01-16 09:33 UTC, nadiakhoptiuk approved these changes

2024-01-16 09:33 UTC, nadiakhoptiuk commented on src/components/ui/FeedbackCard/FeedbackCard.tsx
> +import data from "@/data/feedback.json";
перемістити вище за картинку

2024-01-16 09:35 UTC, nadiakhoptiuk commented
> !!! додатково:
> 
> 1. червона консоль, розбіжності дом-дерева, невірно вкладені теги
>    https://prnt.sc/Ue5zvDyv90-9
> 2. https://prnt.sc/YsHhhB2tLLIZ слайдер поламався
> 3. лінія у футері не повинна бути на всю секцію згідно з макетом:
>    https://prnt.sc/9DEfiEAxnoXI
> 4. кнопка в герої невірно спозиціонована (декстоп, таблет, мобільний).
>    https://prnt.sc/lY_oHPdjZOow
>    https://prnt.sc/TABX-7_66RHy
> 5. картинка в секції Про нас сплющується і розтягується при зміні ширини екрану

тут усе виправлено.
Зливаю.
Наступні зауваження:

1. виправити помилку у назві: FaqListIem
2. border-none у FaqListIem виправити на border-transparent
3. бажано зробити елементи інтерактивними для фокусу з клавіатури
4. такі маленькі компоненти, як SliderNavButton, краще тримати в ui
5. Css модулі називаємо з великої, такі як hero.module.css
6. у нас tailwind як основна бібліотека для стилів, звикайте:
https://prnt.sc/iiVR837NbODW
https://prnt.sc/XrYQD3N5Fpv4
7. секція Героя - не обмежуємо ширину секції, а встановлюємо ширину фонового зображення
8. соцмережі не по сітці https://prnt.sc/A6Rrib_U7sMn
9. лінію у футері в ідеалі реалізувати через псевдоелемент, а не бордер
10. https://prnt.sc/O00ZuTQUkiAN тут марджин не дуже красиво використовувати. можна підкорегувати падінг, або змістити, задавши релатів позиціонування, чи translate
11. кнопка меню - висоту також збільшити
12. якщо на макеті line height до десятих/сотих - округляйте https://prnt.sc/5nOcE2pg-ZKl

FeedbackCard подивлюсь пізніше, розкоментую на сторінці, по коду дещо написала в ПР 33

2024-01-16 09:36 UTC, merged

2024-01-16 13:05 UTC, sergio-nezhigay commented on src/components/ui/FeedbackCard/FeedbackCard.tsx
> +import data from "@/data/feedback.json";
перемістив