Feature/footer
SoftRyzen-internship/gift-studio pull request #34
Opened 2024-01-12 17:15 UTC by TrueMolni

add footer, footer data

2024-01-13 08:24 UTC, sergio-nezhigay commented on src/layout/Footer/Footer.tsx
> +    <footer className="border-t-[1px] border-accent pb-6 pt-[36px] md:py-9 lg:pt-6">
border не на всю ширину на мобілці

2024-01-13 08:31 UTC, sergio-nezhigay commented on src/layout/Footer/Footer.tsx
> +          <a href="https://softryzen.com/">{madeBy}</a>
анімація на ховер фокусі, font size, line height

2024-01-13 08:43 UTC, sergio-nezhigay requested changes
2- помилки

2024-01-13 08:44 UTC, merged

2024-01-14 20:37 UTC, TrueMolni commented on src/layout/Footer/Footer.tsx
> +          <a href="https://softryzen.com/">{madeBy}</a>
додав в feature/services

2024-01-14 20:37 UTC, TrueMolni commented on src/layout/Footer/Footer.tsx
> +    <footer className="border-t-[1px] border-accent pb-6 pt-[36px] md:py-9 lg:pt-6">
додав в feature/services