Feature/readme
SoftRyzen-internship/gift-studio pull request #62
Opened 2024-01-18 15:55 UTC by TrueMolni

2024-01-18 16:02 UTC, sergio-nezhigay requested changes
завтра ще гляну, поки ось мень зламалося-
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/58699786/91e4bbd3-7e8e-41a1-b052-d9837f1260e1)

2024-01-19 11:39 UTC, sergio-nezhigay commented on src/data/contacts.json
> +    "ariaLabel": "+380981234567"
має братись з бекенду

2024-01-19 11:39 UTC, sergio-nezhigay commented on src/data/contacts.json
> +    "ariaLabel": "support@gift.com.ua"
має братись з бекенду (співпадає з email)

2024-01-19 11:41 UTC, sergio-nezhigay commented on src/layout/Header/Header.tsx
> +              customStyle={"hidden md:flex md:ml-[139px] md:mr-auto lg:mr-0"}
перевірити розмір та може замінити ml-[139px] на ml-auto
![image](https://github.com/SoftRyzen-internship/gift-studio/assets/58699786/95a5ad0d-e806-4677-ab41-c895d854996b)

2024-01-19 11:43 UTC, sergio-nezhigay requested changes
не має в змінних дублюватись інфорація що є на бекенді (телефон на email)

2024-01-19 12:17 UTC, TrueMolni commented on src/data/contacts.json
> +    "ariaLabel": "+380981234567"
Змінив

2024-01-19 12:18 UTC, TrueMolni commented on src/data/contacts.json
> +    "ariaLabel": "support@gift.com.ua"
Змінив

2024-01-19 12:27 UTC, merged