Feature/navbar
SoftRyzen-internship/gift-studio pull request #9
Opened 2024-01-05 20:26 UTC by TrueMolni

add sizes to navbar

2024-01-06 08:14 UTC, sergio-nezhigay requested changes
ніколи не робив ревью, прошу пробачати та поправляти мене якщо що...

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +          <li key={id} className="">
className="" не має бути

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +              href="#"
href може не просто решітка а типу #faq

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:w-[508px] lg:h-[20px]";
lg:w-[508px] lg:h-[20px] фіксовані - не впевнений що норм.

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +  const mobileStyles = "lg:hidden flex w-[123px] h-[294px] mx-auto";
w-[123px] h-[294px] фіксовані - не впевнений що норм.

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +import data from "../../data/navbar.json";
замінити на "@/data/navbar.json"; треба додати "@/data/": ["src/data/"], до tsconfig.json

2024-01-06 08:14 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +    <nav className={!isMobile ? desktopStyles : mobileStyles}>
можливо isMobile зайвий. А може без JS буде менш зрозуміло, не знаю

2024-01-06 19:35 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +    <nav className={!isMobile ? desktopStyles : mobileStyles}>
він буде потрібний для mobile menu, модна реалізувати по-іншому

2024-01-06 19:35 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +import data from "../../data/navbar.json";
Зробив

2024-01-06 19:36 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +  const mobileStyles = "lg:hidden flex w-[123px] h-[294px] mx-auto";
змінив поки на w-max та h-max

2024-01-06 19:36 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:w-[508px] lg:h-[20px]";
змінив поки на w-max та h-max

2024-01-06 19:37 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +              href="#"
тут href просто позначає, що це якір, сам не повністю розумію, а сам текст посилання йде в атрибут "to"

2024-01-06 19:43 UTC, TrueMolni commented on src/components/ui/NavBar.tsx
> +          <li key={id} className="">
Прибрав

2024-01-06 19:52 UTC, TrueMolni commented
Зробив зміни

2024-01-07 07:38 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +  const desktopStyles = "hidden lg:flex lg:w-max[508px] lg:h-max[20px]";
замість w-max правильно max-w. Але це те саме що й просто ширина. Краще, здається, w-fit. На випадок коли зміниться наприклад кількість пуктів меню. Й з висотою теж можна щоб не обмежуватись поставити block в посиланні внизу

2024-01-07 07:39 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +  const mobileStyles = "lg:hidden flex w-max-[123px] h-max-[294px] mx-auto";
те ж саме

2024-01-07 07:40 UTC, sergio-nezhigay commented on src/components/ui/NavBar.tsx
> +    <nav className={!isMobile ? desktopStyles : mobileStyles}>
ок

2024-01-07 07:59 UTC, sergio-nezhigay approved these changes

2024-01-07 07:59 UTC, merged